--
-- PostgreSQL database dump
--

\restrict MQUmMvfJROTPdRyPB0XzgISGITwvx6f5iohnhxgTRuShZtj8sLhQJCmr7IKinvN

-- Dumped from database version 18.4 (Debian 18.4-1.pgdg13+1)
-- Dumped by pg_dump version 18.4 (Debian 18.4-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: aktualizuj_daty_audytowe(); Type: FUNCTION; Schema: public; Owner: postgres
--

CREATE FUNCTION public.aktualizuj_daty_audytowe() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN

    IF TG_OP = 'INSERT' THEN

        NEW.datautworzenia := CURRENT_TIMESTAMP;
        NEW.datamodyfikacji := CURRENT_TIMESTAMP;

    ELSIF TG_OP = 'UPDATE' THEN

        NEW.datautworzenia := OLD.datautworzenia;
        NEW.datamodyfikacji := CURRENT_TIMESTAMP;

    END IF;

    RETURN NEW;

END;
$$;


ALTER FUNCTION public.aktualizuj_daty_audytowe() OWNER TO postgres;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: dim_czas; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.dim_czas (
    czas_key integer NOT NULL,
    data date NOT NULL,
    dzien integer NOT NULL,
    miesiac integer NOT NULL,
    nazwa_miesiaca character varying(20) NOT NULL,
    kwartal integer NOT NULL,
    rok integer NOT NULL,
    datautworzenia timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    datamodyfikacji timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT chk_czas_dzien CHECK (((dzien >= 1) AND (dzien <= 31))),
    CONSTRAINT chk_czas_kwartal CHECK (((kwartal >= 1) AND (kwartal <= 4))),
    CONSTRAINT chk_czas_miesiac CHECK (((miesiac >= 1) AND (miesiac <= 12)))
);


ALTER TABLE public.dim_czas OWNER TO postgres;

--
-- Name: dim_czas_czas_key_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.dim_czas ALTER COLUMN czas_key ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.dim_czas_czas_key_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: dim_dokument; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.dim_dokument (
    dokument_key integer NOT NULL,
    dokument_id integer NOT NULL,
    numerdokumentu character varying(100) NOT NULL,
    data_wystawienia date NOT NULL,
    data_ksiegowania date NOT NULL,
    opis character varying(500),
    datautworzenia timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    datamodyfikacji timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


ALTER TABLE public.dim_dokument OWNER TO postgres;

--
-- Name: dim_dokument_dokument_key_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.dim_dokument ALTER COLUMN dokument_key ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.dim_dokument_dokument_key_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: dim_konto; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.dim_konto (
    konto_key integer NOT NULL,
    konto_id integer NOT NULL,
    numerkonta character varying(50) NOT NULL,
    nazwakonta character varying(255) NOT NULL,
    typkonta character varying(50),
    datautworzenia timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    datamodyfikacji timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


ALTER TABLE public.dim_konto OWNER TO postgres;

--
-- Name: dim_konto_konto_key_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.dim_konto ALTER COLUMN konto_key ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.dim_konto_konto_key_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: dim_kontrahent; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.dim_kontrahent (
    kontrahent_key integer NOT NULL,
    kontrahent_id integer NOT NULL,
    nazwa character varying(255) NOT NULL,
    nip character varying(20),
    adres character varying(500),
    typkontrahenta character varying(50),
    datautworzenia timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    datamodyfikacji timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


ALTER TABLE public.dim_kontrahent OWNER TO postgres;

--
-- Name: dim_kontrahent_kontrahent_key_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.dim_kontrahent ALTER COLUMN kontrahent_key ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.dim_kontrahent_kontrahent_key_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: etl_log; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.etl_log (
    etl_log_id bigint NOT NULL,
    process_name character varying(100) NOT NULL,
    start_time timestamp without time zone NOT NULL,
    end_time timestamp without time zone,
    status character varying(20) NOT NULL,
    rows_processed integer DEFAULT 0 NOT NULL,
    error_message text
);


ALTER TABLE public.etl_log OWNER TO postgres;

--
-- Name: etl_log_etl_log_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.etl_log_etl_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.etl_log_etl_log_id_seq OWNER TO postgres;

--
-- Name: etl_log_etl_log_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.etl_log_etl_log_id_seq OWNED BY public.etl_log.etl_log_id;


--
-- Name: etl_watermark; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.etl_watermark (
    process_name character varying(100) NOT NULL,
    last_successful_run timestamp without time zone
);


ALTER TABLE public.etl_watermark OWNER TO postgres;

--
-- Name: fact_operacja; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.fact_operacja (
    operacja_key bigint NOT NULL,
    czas_key integer NOT NULL,
    kontrahent_key integer NOT NULL,
    konto_key integer NOT NULL,
    dokument_key integer NOT NULL,
    pozycja_id integer NOT NULL,
    kwota numeric(15,2) NOT NULL,
    strona character varying(2) NOT NULL,
    opis character varying(500),
    datautworzenia timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    datamodyfikacji timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT chk_fact_kwota CHECK ((kwota >= (0)::numeric)),
    CONSTRAINT chk_fact_strona CHECK (((strona)::text = ANY ((ARRAY['WN'::character varying, 'MA'::character varying])::text[])))
);


ALTER TABLE public.fact_operacja OWNER TO postgres;

--
-- Name: fact_operacja_operacja_key_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.fact_operacja ALTER COLUMN operacja_key ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.fact_operacja_operacja_key_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: etl_log etl_log_id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.etl_log ALTER COLUMN etl_log_id SET DEFAULT nextval('public.etl_log_etl_log_id_seq'::regclass);


--
-- Name: dim_czas dim_czas_data_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.dim_czas
    ADD CONSTRAINT dim_czas_data_key UNIQUE (data);


--
-- Name: dim_czas dim_czas_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.dim_czas
    ADD CONSTRAINT dim_czas_pkey PRIMARY KEY (czas_key);


--
-- Name: dim_dokument dim_dokument_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.dim_dokument
    ADD CONSTRAINT dim_dokument_pkey PRIMARY KEY (dokument_key);


--
-- Name: dim_konto dim_konto_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.dim_konto
    ADD CONSTRAINT dim_konto_pkey PRIMARY KEY (konto_key);


--
-- Name: dim_kontrahent dim_kontrahent_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.dim_kontrahent
    ADD CONSTRAINT dim_kontrahent_pkey PRIMARY KEY (kontrahent_key);


--
-- Name: etl_log etl_log_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.etl_log
    ADD CONSTRAINT etl_log_pkey PRIMARY KEY (etl_log_id);


--
-- Name: etl_watermark etl_watermark_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.etl_watermark
    ADD CONSTRAINT etl_watermark_pkey PRIMARY KEY (process_name);


--
-- Name: fact_operacja fact_operacja_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.fact_operacja
    ADD CONSTRAINT fact_operacja_pkey PRIMARY KEY (operacja_key);


--
-- Name: dim_dokument uq_dim_dokument_id; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.dim_dokument
    ADD CONSTRAINT uq_dim_dokument_id UNIQUE (dokument_id);


--
-- Name: dim_dokument uq_dim_dokument_source; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.dim_dokument
    ADD CONSTRAINT uq_dim_dokument_source UNIQUE (dokument_id);


--
-- Name: dim_konto uq_dim_konto_id; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.dim_konto
    ADD CONSTRAINT uq_dim_konto_id UNIQUE (konto_id);


--
-- Name: dim_konto uq_dim_konto_source; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.dim_konto
    ADD CONSTRAINT uq_dim_konto_source UNIQUE (konto_id);


--
-- Name: dim_kontrahent uq_dim_kontrahent_id; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.dim_kontrahent
    ADD CONSTRAINT uq_dim_kontrahent_id UNIQUE (kontrahent_id);


--
-- Name: dim_kontrahent uq_dim_kontrahent_source; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.dim_kontrahent
    ADD CONSTRAINT uq_dim_kontrahent_source UNIQUE (kontrahent_id);


--
-- Name: fact_operacja uq_fact_operacja_pozycja_id; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.fact_operacja
    ADD CONSTRAINT uq_fact_operacja_pozycja_id UNIQUE (pozycja_id);


--
-- Name: fact_operacja uq_fact_pozycja; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.fact_operacja
    ADD CONSTRAINT uq_fact_pozycja UNIQUE (pozycja_id);


--
-- Name: idx_fact_operacja_czas; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_fact_operacja_czas ON public.fact_operacja USING btree (czas_key);


--
-- Name: idx_fact_operacja_dokument; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_fact_operacja_dokument ON public.fact_operacja USING btree (dokument_key);


--
-- Name: idx_fact_operacja_konto; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_fact_operacja_konto ON public.fact_operacja USING btree (konto_key);


--
-- Name: idx_fact_operacja_kontrahent; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_fact_operacja_kontrahent ON public.fact_operacja USING btree (kontrahent_key);


--
-- Name: idx_fact_operacja_strona; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_fact_operacja_strona ON public.fact_operacja USING btree (strona);


--
-- Name: dim_czas trg_dim_czas_daty_audytowe; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER trg_dim_czas_daty_audytowe BEFORE INSERT OR UPDATE ON public.dim_czas FOR EACH ROW EXECUTE FUNCTION public.aktualizuj_daty_audytowe();


--
-- Name: dim_dokument trg_dim_dokument_daty_audytowe; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER trg_dim_dokument_daty_audytowe BEFORE INSERT OR UPDATE ON public.dim_dokument FOR EACH ROW EXECUTE FUNCTION public.aktualizuj_daty_audytowe();


--
-- Name: dim_konto trg_dim_konto_daty_audytowe; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER trg_dim_konto_daty_audytowe BEFORE INSERT OR UPDATE ON public.dim_konto FOR EACH ROW EXECUTE FUNCTION public.aktualizuj_daty_audytowe();


--
-- Name: dim_kontrahent trg_dim_kontrahent_daty_audytowe; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER trg_dim_kontrahent_daty_audytowe BEFORE INSERT OR UPDATE ON public.dim_kontrahent FOR EACH ROW EXECUTE FUNCTION public.aktualizuj_daty_audytowe();


--
-- Name: fact_operacja trg_fact_operacja_daty_audytowe; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER trg_fact_operacja_daty_audytowe BEFORE INSERT OR UPDATE ON public.fact_operacja FOR EACH ROW EXECUTE FUNCTION public.aktualizuj_daty_audytowe();


--
-- Name: fact_operacja fk_fact_czas; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.fact_operacja
    ADD CONSTRAINT fk_fact_czas FOREIGN KEY (czas_key) REFERENCES public.dim_czas(czas_key);


--
-- Name: fact_operacja fk_fact_dokument; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.fact_operacja
    ADD CONSTRAINT fk_fact_dokument FOREIGN KEY (dokument_key) REFERENCES public.dim_dokument(dokument_key);


--
-- Name: fact_operacja fk_fact_konto; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.fact_operacja
    ADD CONSTRAINT fk_fact_konto FOREIGN KEY (konto_key) REFERENCES public.dim_konto(konto_key);


--
-- Name: fact_operacja fk_fact_kontrahent; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.fact_operacja
    ADD CONSTRAINT fk_fact_kontrahent FOREIGN KEY (kontrahent_key) REFERENCES public.dim_kontrahent(kontrahent_key);


--
-- PostgreSQL database dump complete
--

\unrestrict MQUmMvfJROTPdRyPB0XzgISGITwvx6f5iohnhxgTRuShZtj8sLhQJCmr7IKinvN

